#!/bin/bash
# part of zabbix-nameservers
#tony20181129 discover configured nameservers

N=0
echo -n "{\"data\":[" 
grep ^nameserver /etc/resolv.conf| awk '{ print $2 }' | while read i
do
    if [ $N -gt 0 ]
    then
        echo -n ","
    fi
    echo -n "{\"{#N}\":$N,\"{#DNSSERVER}\":\"$i\"}"
    N=$((N + 1))
done

echo -n "]}"

